services:
  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: watermark-backend
    ports:
      - "5051:5050"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - watermark-network

  # Frontend Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: watermark-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - watermark-network

networks:
  watermark-network:
    driver: bridge

